version: '3.7'  # Specify the Docker Compose version

networks:
  projectm:
    driver: bridge

volumes:
  baseservice_postgresql-vl:

services:
  projectm_baseservice_service:
    container_name: baseservice_service
    build:
      context: .  # Current directory
      dockerfile: docker/BaseServiceDev.Dockerfile  # The Dockerfile to use
    ports:
      - "8080:80"  # Map port 5000 on host to port 80 on container
    volumes:
      - ./BaseService:/app  # Bind mount the current directory to the /app directory in the container
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"  # Set the environment variable
      ASPNETCORE_URLS: "http://baseservice_service:80"
    networks:
      - projectm

  projectm_baseservice_postgresql:
    image: postgres:18
    restart: unless-stopped
    container_name: baseservice_postgresql #host for pgadmin
    ports:
      - 5432:5432
    volumes:
      - baseservice_postgresql-vl:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db-init-baseservice"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - projectm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db-init"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  projectm_apigateway_service:
    container_name: apigateway_service
    build:
      context: .  # Current directory
      dockerfile: docker/ApiGateway.Dockerfile  # The Dockerfile to use
    ports:
      - "5000:5000"  # Map port 5000 on host to port 80 on container
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"  # Set the environment variable
      ASPNETCORE_URLS: "http://apigateway_service:5000"
    networks:
      - projectm