version: '3.7'  # Specify the Docker Compose version

services:
  projectm_baseservice_service:
    container_name: baseservice_service
    build:
      context: .  # Current directory
      dockerfile: docker/BaseService.Dockerfile  # The Dockerfile to use
    ports:
      - "8080:80"  # Map port 5000 on host to port 80 on container
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"  # Set the environment variable
      ASPNETCORE_URLS: "http://baseservice_service:80"
    networks:
      - default

networks:
  default: