version: '3.7'  # Specify the Docker Compose version

networks:
  projectm:
    external: true  # Указываем, что это внешняя сеть

volumes:
  baseservice_postgresql-vl:

services:
  projectm_nginx:
    image: nginx:1.29.4
    container_name: project_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-conf/${NGINXFILE}:/etc/nginx/conf.d/default.conf
    networks:
      - projectm
  
  projectm_apigateway_service:
    container_name: apigateway_service
    build:
      context: .  # Current directory
      dockerfile: docker/ApiGateway.Dockerfile  # The Dockerfile to use
    restart: unless-stopped
    ports:
      - "5000:5000"  # Map port 5000 on host to port 80 on container
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"  # Set the environment variable
      ASPNETCORE_URLS: "http://apigateway_service:5000"
    networks:
      - projectm

  projectm_baseservice_service:
    container_name: baseservice_service
    build:
      context: .  # Current directory where docker-compose.yml file
      dockerfile: ${DOCFILEBASESERVICE}  # The Dockerfile to use
    restart: unless-stopped
    ports:
      - "8080:80"  # Map port 5000 on host to port 80 on container
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETENV}  # Set the environment variable
      ASPNETCORE_URLS: "http://baseservice_service:80"
    volumes:
      - ../files:/app/wwwroot  # Монтируем статическую папку
    networks:
      - projectm
    depends_on:
      - projectm_baseservice_postgresql

  projectm_baseservice_postgresql:
    image: postgres:18
    container_name: baseservice_postgresql #host for pgadmin
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - baseservice_postgresql-vl:/var/lib/postgresql/data
      - ./BaseServiceDb/db-init_dump.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_DB: "base-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - projectm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d base-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s